### ISSUE TITLE
Behuizing zelf laser cutten / Laser cut housing

### ISSUE THREAD

**Issue by tomvanbraeckel** [seeseemelk/robox#5]
(English below)

Hoi, wij waren vorig weekend op Fri3D camp 2022 maar de Bluetooth sessie zat al veel op voorhand volzet...

We zouden het graag zelf maken maar vinden op deze github de behuizing niet terug en het was net de behuizing die we zo leuk vonden, met dat robot gezichtje :-)

Zouden jullie de behuizing online kunnen zetten? Of staat ze al online en hebben we erover gekeken?

Alvast hartelijk bedankt!

PS: zet er gerust een donatie adres bij :-)

***

Hi, we were at Fri3D camp 2022 last weekend but the Bluetooth session was full way in advance...

We would love to make it ourselves but can't find the housing on this github and it was especially the housing which we liked so much, with that robot face :-)

Could you please put the housing online? Or is it already online and we've just overlooked it?

Thanks in advance!

PS: feel free to add a donation address :-)

**Comment by WouterVandeWiele** [comment]
Goed om ons er aan te herinneren. We zullen de lasercut files, alsook de 3D geprinte onderdelen (voor de oogjes, micro switches en montage van de PCB en behuizing, in de loop van deze week online zetten.

**Comment by tomvanbraeckel** [comment]
Dat is super goed nieuws, bedankt!

**Comment by parsupo** [comment]
Ze staan nu allemaal online denk ik:
[hw+3D-printing+laser-cutting-files](https://github.com/seeseemelk/robox/wiki/Hardware-description)

**Comment by WouterVandeWiele** [comment]
Goed nieuw: de files staan nu in de documentation folder:
https://github.com/seeseemelk/robox/tree/master/documentation
* * * 
3D print files and lastercut files are now available

**Comment by tomvanbraeckel** [comment]
Perfect! Ik heb ze geimporteerd in Freecad en een extrude gedaan, zo kan ik ze 3D printen in plaats van te cutten ;-)

Nog 1 vraagje: hoe dik moet het gelasercut (of geextrude) worden? 3mm? 4mm?

**Comment by parsupo** [comment]
Ik heb ook nog een step file van het volledige model gepusht. Dat is misschien gemakkelijker om de zijkant te printen. De triplex was 3mm dik maar dit varieerde soms tot 3.5mm. De lasercut files printen en plooien kan tricky zijn.

**Comment by tomvanbraeckel** [comment]
Dat 3D model is geweldig, inderdaad ideaal, nogmaals bedankt!

**Comment by parsupo** [comment]
Voor donaties hebben we nu ook ondersteuning toegevoegd. Uiteraard volledig vrijblijven.
[zie hier op de main page](https://github.com/seeseemelk/robox/wiki)

**Comment by tomvanbraeckel** [comment]
Done!

**Comment by parsupo** [comment]
Many thanks!
